### ISSUE TITLE
Segmentation fault when solving AMPL model

### ISSUE THREAD

**Issue by frapac** [pjssilva/NLPModelsAlgencan.jl#11]
Hi, 
First, thank you for developing this wrapper to Algencan, it has proven to be very useful for a project I am working on. 

I am opening this issue as I am facing a segmentation fault when solving an Ampl instance using `AmplNLReader.jl`.
The instance is `gnash10` from [MacMPEC](http://www.mcs.anl.gov/~leyffer/macmpec/MacMPEC-nl.tar.gz). A MWE is:
```julia
using NLPModelsAlgencan
using AmplNLReader

src_dir = "/path/to/MacMPEC/"
instance = joinpath(src_dir, "gnash10.nl")
nlp = AmplModel(instance)
results = algencan(model)

```
I have the following stacktrace (keeping only the meaningful part): 
```
 Entry to ALGENCAN.                                                                                                                                                          12:55:05 [35/1748]
 Number of variables  :      13                                                                
 Number of constraints:      12                                                                
                                                                                               
out penalt  objective infeas  scaled    scaled infeas norm   |Grad| inner Newton               
ite         function  ibilty  obj-funct infeas +compl graLag infeas totit forKKT               
  0        -3.859D+03 6.D+01 -5.789D+01 3.D+01 3.D+01 1.D+00 8.D+01    0   0   0               
                                                                                               
[24760] signal (11.1): Segmentation fault                                                      
in expression starting at REPL[3]:1                                                            
deriv_errchk_ASL at /home/fpacaud/.julia/artifacts/552b43f8dea17007536f11ed23b39fb7e97bec6b/lib/libasl.so (unknown line)
jacpval_ASL at /home/fpacaud/.julia/artifacts/552b43f8dea17007536f11ed23b39fb7e97bec6b/lib/libasl.so (unknown line)
asl_jacval at /home/fpacaud/.julia/artifacts/552b43f8dea17007536f11ed23b39fb7e97bec6b/lib/libasl.so (unknown line)
jac_coord! at /home/fpacaud/dev/AmplNLReader.jl/src/ampl_model.jl:7                            
jac_coord at /home/fpacaud/.julia/packages/NLPModels/FNnIq/src/nlp/api.jl:261                  
unknown function (ip: 0x7f9da3359849)                                                          
_jl_invoke at /cache/build/builder-amdci4-0/julialang/julia-release-1-dot-10/src/gf.c:2895 [inlined]
ijl_apply_generic at /cache/build/builder-amdci4-0/julialang/julia-release-1-dot-10/src/gf.c:3077
julia_gjac at /home/fpacaud/.julia/packages/NLPModelsAlgencan/v69gG/src/NLPModelsAlgencan.jl:494
#3 at /home/fpacaud/.julia/packages/NLPModelsAlgencan/v69gG/src/NLPModelsAlgencan.jl:139       
unknown function (ip: 0x7f9da33551b4)                                                          
__c_algencan_wrapper_MOD_f__evalgjac at /home/fpacaud/.julia/packages/NLPModelsAlgencan/v69gG/deps/usr/lib/libalgencan.so (unknown line)
__problvlv_MOD_vevalgjac at /home/fpacaud/.julia/packages/NLPModelsAlgencan/v69gG/deps/usr/lib/libalgencan.so (unknown line)
__problvls_MOD_sevalgjac at /home/fpacaud/.julia/packages/NLPModelsAlgencan/v69gG/deps/usr/lib/libalgencan.so (unknown line)
sevalnl_ at /home/fpacaud/.julia/packages/NLPModelsAlgencan/v69gG/deps/usr/lib/libalgencan.so (unknown line)
sevalnal_ at /home/fpacaud/.julia/packages/NLPModelsAlgencan/v69gG/deps/usr/lib/libalgencan.so (unknown line)
calcnal_ at /home/fpacaud/.julia/packages/NLPModelsAlgencan/v69gG/deps/usr/lib/libalgencan.so (unknown line)
extrapolation_ at /home/fpacaud/.julia/packages/NLPModelsAlgencan/v69gG/deps/usr/lib/libalgencan.so (unknown line)
tnls_ at /home/fpacaud/.julia/packages/NLPModelsAlgencan/v69gG/deps/usr/lib/libalgencan.so (unknown line)
gencan_ at /home/fpacaud/.julia/packages/NLPModelsAlgencan/v69gG/deps/usr/lib/libalgencan.so (unknown line)
auglag_ at /home/fpacaud/.julia/packages/NLPModelsAlgencan/v69gG/deps/usr/lib/libalgencan.so (unknown line)
algencan_ at /home/fpacaud/.julia/packages/NLPModelsAlgencan/v69gG/deps/usr/lib/libalgencan.so (unknown line)
c_algencan at /home/fpacaud/.julia/packages/NLPModelsAlgencan/v69gG/deps/usr/lib/libalgencan.so (unknown line)
#algencan#1 at /home/fpacaud/.julia/packages/NLPModelsAlgencan/v69gG/src/NLPModelsAlgencan.jl:240
```

**Comment by pjssilva** [comment]
Hi, @frapac. 

I was able to reproduce the error here. I confess that I am not the best reader of stacktraces. But I understand that the first line of the stacktrace is where the Segmentation fault occurred. If I read it correctly, it took place at the `deriv_errchk_ASL function` in `libasl.so` which is the Ampl Solver Library. So, maybe asl is to blame?

**Comment by frapac** [comment]
Julia's stacktrace can be a bit too verbose indeed... I think you are correct to assume that the error took place in `libasl.so`. 

I can solve the same instance with other solvers without any trouble. I suspect something is going on inside Algencan: my guess is that the vector of values we sent to ASL to evaluate the Jacobian is not long enough, hence the segfault when we do the derivatives check. But that's just an intuition. Let me know if you want me to have a closer look.

**Comment by pjssilva** [comment]
You might be right. I have to think how to verify this. Probably the best route would be to capture the call to evaluate the Jacobian and print some information about the size of the vector that `NLPModelsAlgencan` is "allocating" for that. Let me think for a while. Unfortunately, I have many tasks in my to-do list. So it might take a couple of days.

**Comment by pjssilva** [comment]
Hi, @frapac. I have spent some time debugging this error today. I am now quite sure the problem is not associated to `NLPModelsAlgencan` as I can reproduce the error without it. To achieve this, just run the program below after downloading and extracting the file `x.zip` that has inside a file named `x.jls` with the serialized version of the vector where the error occurs. Note that the program only loads `AmplNLReader` and `NLPModels`.  So, the error is either in them (unlikely) or in the AMPL binary library. 

[x.zip](https://github.com/user-attachments/files/17297676/x.zip)

Please confirm that you can reproduce the bug in your computer so that I can close this issue.

```julia
using NLPModels
using AmplNLReader
using Serialization

nlp = AmplModel("gnash10.nl")
x = deserialize("x.jls")
f_grad = zero(x)
grad!(nlp, x, f_grad)
jac_coord(nlp, x)
```

**Comment by frapac** [comment]
Hi @pjssilva ! Thank for coming back to this issue. 
I just run your MWE on my computer, I confirm I can reproduce the segfault locally. 
So you are right, this is not an issue with Algencan. I will transfer the issue to AmplNLReader.jl. Closing this now. 

Thank you for your help.
